---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/6 11:25
---

local BackpackView = {}

local backpack_panel = nil
local backpack_content = nil
local backpack_btn_add = nil
local backpack_btn_sub = nil
local backpack_btn_num_add = nil
local backpack_btn_num_sub = nil

function BackpackView.addItem(index)
    local backpack_item = Resource.load('backpack_item')
    local backpack_item_content = {}
    backpack_item_content.img = backpack_item.transform:Find('img'):GetComponent('Image')
    backpack_item_content.mask = backpack_item.transform:Find('mask').gameObject
    backpack_item_content.btn = backpack_item.transform:Find('btn'):GetComponent('Button')
    backpack_item_content.num = backpack_item.transform:Find('txt_num'):GetComponent(typeof(CS.UnityEngine.UI.Text))

    table.insert(BackpackView.itemsContent, index, backpack_item_content)
    table.insert(BackpackView.items, index, backpack_item)

    backpack_item_content.mask:SetActive(false)
    backpack_item_content.img.sprite = Resource.loadImage(BackpackModel.items[index].name)
    backpack_item_content.num.text = BackpackModel.curItems[index].num

    -- 物品点击事件
    backpack_item_content.btn.onClick:AddListener(function()
        -- 判断当前穿戴物品是否被删除
        if BackpackView.itemsContent[BackpackModel.curItemID] then
            BackpackView.itemsContent[BackpackModel.curItemID].mask:SetActive(false)
        end

        for k, v in pairs(BackpackView.itemsContent) do
            if v == backpack_item_content then
                BackpackModel.curItemID = k
                break
            end
        end

        EventCenter.SendEvent(EventCenter.Type.SetCharacterImage, BackpackView.itemsContent[BackpackModel.curItemID].img.sprite)
        BackpackView.itemsContent[BackpackModel.curItemID].mask:SetActive(true)
    end)
end

function BackpackView.subItem(index)
    Resource.destroy(BackpackView.items[index])
    BackpackView.items[index] = nil
    BackpackView.itemsContent[index] = nil

    if BackpackModel.curItemID == index then
        EventCenter.SendEvent(EventCenter.Type.SetCharacterImage, nil)
    end
end

function BackpackView.updateItem(index, num)
    BackpackView.itemsContent[index].num.text = num
end

function BackpackView.setCurState()
    if not BackpackView.itemsContent[BackpackModel.curItemID] then
        return
    end
    EventCenter.SendEvent(EventCenter.Type.SetCharacterImage, BackpackView.itemsContent[BackpackModel.curItemID].img.sprite)
    BackpackView.itemsContent[BackpackModel.curItemID].mask:SetActive(true)
end

function BackpackView.show(panel)
    if backpack_panel then
        BackpackView.hide()
        return
    end
    backpack_panel = panel
    BackpackView.init()
end

function BackpackView.hide()
    backpack_panel = nil
    UIManager.hidePanel('backpack_panel')
end

function BackpackView.init()
    backpack_content = backpack_panel.transform:Find('Viewport/Content')
    backpack_btn_add = backpack_panel.transform:Find('btn_add'):GetComponent('Button')
    backpack_btn_sub = backpack_panel.transform:Find('btn_sub'):GetComponent('Button')
    backpack_btn_num_add = backpack_panel.transform:Find('btn_num_add'):GetComponent('Button')
    backpack_btn_num_sub = backpack_panel.transform:Find('btn_num_sub'):GetComponent('Button')

    BackpackView.items = {} -- 存放背包内物品对象
    BackpackView.itemsContent = {} -- 存放背包内物品属性 image button mask

    backpack_btn_add.onClick:AddListener(function()
        BackpackController.addClick(function(index)
            BackpackView.addItem(index)
        end)
    end)

    backpack_btn_sub.onClick:AddListener(function()
        BackpackController.subClick(function(index)
            BackpackView.subItem(index)
        end)
    end)

    backpack_btn_num_add.onClick:AddListener(function()
        BackpackController.numAddClick(function(index, num)
            BackpackView.updateItem(index, num)
        end)
    end)

    backpack_btn_num_sub.onClick:AddListener(function()
        BackpackController.numSubClick(function(index, num)
            BackpackView.updateItem(index, num)
        end)
    end)

    for i = 1, BackpackModel.curItemCount do
        BackpackView.addItem(i)
    end

    BackpackView.setCurState()
end

return BackpackView
