---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/6 11:25
---

local BackpackView = {}

local backpack_panel = home_panel.transform:Find('backpack_panel').gameObject
local backpack_content = home_panel.transform:Find('backpack_panel/Viewport/Content')
local backpack_btn_add = home_panel.transform:Find('backpack_panel/btn_add'):GetComponent('Button')
local backpack_btn_sub = home_panel.transform:Find('backpack_panel/btn_sub'):GetComponent('Button')

BackpackView.items = {} -- 存放背包内物品对象
BackpackView.itemsContent = {} -- 存放背包内物品属性 image button mask

backpack_btn_add.onClick:AddListener(function()
    BackpackController.addClick()
end)

backpack_btn_sub.onClick:AddListener(function()
    BackpackController.subClick()
end)

-- 第一次启动时初始化
function BackpackView.firstInit()
    for i = 1, BackpackModel.curItemCount do
        BackpackView.addItem(i)
    end
    BackpackView.init()
end

function BackpackView.addItem(index)
    local item = CS.UnityEngine.Resources.Load('Prefabs/backpack_item', typeof(CS.UnityEngine.GameObject))
    local backpack_item = CS.UnityEngine.Object.Instantiate(item, backpack_content.gameObject.transform);
    local backpack_item_content = {}
    backpack_item_content.img = backpack_item.transform:Find('img'):GetComponent('Image')
    backpack_item_content.mask = backpack_item.transform:Find('mask').gameObject
    backpack_item_content.btn = backpack_item.transform:Find('btn'):GetComponent('Button')

    table.insert(BackpackView.itemsContent, index, backpack_item_content)
    table.insert(BackpackView.items, index, backpack_item)

    backpack_item_content.mask:SetActive(false)
    backpack_item_content.img.sprite = CS.UnityEngine.Resources.Load('Backpack/Images/' .. index, typeof(CS.UnityEngine.Sprite))
    
    -- 物品点击事件
    backpack_item_content.btn.onClick:AddListener(function()
        -- 判断当前穿戴物品是否被删除
        if BackpackView.itemsContent[BackpackModel.curItemID] then 
            BackpackView.itemsContent[BackpackModel.curItemID].mask:SetActive(false) 
        end
        
        for k, v in pairs(BackpackView.itemsContent) do
            if v == backpack_item_content then
                BackpackModel.curItemID = k
                break
            end
        end

        HomeView.setCharacterImage(BackpackView.itemsContent[BackpackModel.curItemID].img.sprite)
        BackpackView.itemsContent[BackpackModel.curItemID].mask:SetActive(true)
    end)
end

function BackpackView.subItem(index)
    CS.UnityEngine.Object.Destroy(BackpackView.items[index])
    BackpackView.items[index] = nil
    BackpackView.itemsContent[index] = nil
    if BackpackModel.curItemID == index then
        HomeView.setCharacterImage(nil)
    end
end

function BackpackView.init()
    HomeView.setCharacterImage(BackpackView.itemsContent[BackpackModel.defItemID].img.sprite)
    BackpackView.itemsContent[BackpackModel.defItemID].mask:SetActive(true)
end

function BackpackView.show()
    backpack_panel:SetActive(not backpack_panel.activeSelf)
end

function BackpackView.hide()
    backpack_panel:SetActive(false)
end

BackpackView.firstInit()

return BackpackView
