---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/11 11:07
---

local CharacterView = {}

local img_character = home_panel.transform:Find('character/Image'):GetComponent('Image')
local btn_character = home_panel.transform:Find('character/btn_backpack'):GetComponent('Button')

EventCenter.AddListener(EventCenter.Type.SetCharacterImage, function(param)
    CharacterView.setImage(param)
end)

btn_character.onClick:AddListener(function()
    EventCenter.SendEvent(EventCenter.Type.ShowBackpackPage)
end)

function CharacterView.setImage(sprite)
    img_character.sprite = sprite
end

return CharacterView