---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 14:11
---

local HomeView = {}

local btn_quit = home_panel.transform:Find('btn_quit'):GetComponent('Button')

EventCenter.AddListener(EventCenter.Type.ShowHomePage, function()
    HomeView.show()
end)

btn_quit.onClick:AddListener(function()
    Tips.show('确定退出?', function()
        HomeView.hide()
        EventCenter.SendEvent(EventCenter.Type.ShowLoginPage)
    end, true)
end)

function HomeView.show()
    home_panel:SetActive(true)
end

function HomeView.hide()
    home_panel:SetActive(false)
end

return HomeView