---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 14:11
---

local HomeView = {}

local home_panel = nil
local btn_quit = nil

function HomeView.show(panel)
    home_panel = panel
    HomeView.init()
    home_panel:SetActive(true)
end

function HomeView.init()
    require('Scripts.View.CharacterView').init(home_panel)
    btn_quit = home_panel.transform:Find('btn_quit'):GetComponent('Button')
    btn_quit.onClick:AddListener(function()
        Tips.show('确定退出?', function()
            HomeView.hide()
            UIManager.showPanel('login_panel')
        end, true)
    end)
end

function HomeView.hide()
    UIManager.hidePanel('home_panel')
end

return HomeView