---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 12:10
---

local LoginView = {}

local login_username = login_panel.transform:Find('input_username'):GetComponent("InputField")
local login_password = login_panel.transform:Find('input_password'):GetComponent("InputField")
local login_btn_login = login_panel.transform:Find('btn_login'):GetComponent("Button")
local login_btn_signup = login_panel.transform:Find('btn_signup'):GetComponent("Button")

login_btn_login.onClick:AddListener(function()
    LoginController.loginClick(login_username.text, login_password.text)
end)

login_btn_signup.onClick:AddListener(function()
    LoginController.signupClick()
end)

function LoginView.hide()
    login_panel:SetActive(false)
    login_username.text = ""
    login_password.text = ""
end

function LoginView.show()
    login_panel:SetActive(true)
end

return LoginView