---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 12:11
---

local SignupView = {}

local signup_username = signup_panel.transform:Find('input_username'):GetComponent("InputField")
local signup_password01 = signup_panel.transform:Find('input_password01'):GetComponent("InputField")
local signup_password02 = signup_panel.transform:Find('input_password02'):GetComponent("InputField")
local signup_btn_signup = signup_panel.transform:Find('btn_signup'):GetComponent("Button")
local signup_btn_back = signup_panel.transform:Find('btn_back'):GetComponent("Button")

signup_btn_signup.onClick:AddListener(function()
    SignupController.signupClick(signup_username.text,signup_password01.text,signup_password02.text)
end)

signup_btn_back.onClick:AddListener(function()
    SignupController.backClick()
end)

function SignupView.hide()
    signup_panel:SetActive(false)
    signup_username.text = ""
    signup_password01.text = ""
    signup_password02.text = ""
end 

function SignupView.show()
    signup_panel:SetActive(true)
end 

return SignupView