---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/6 14:05
---

local BackpackController = {}

function BackpackController.addClick()
    if BackpackModel.curItemCount < BackpackModel.maxItemCount then
        BackpackModel.curItemCount = BackpackModel.curItemCount + 1
        BackpackView.addItem(BackpackModel.curItemCount)
    else
        Tips.show('没有可以添加的物品')
    end
end

function BackpackController.subClick()
    if BackpackModel.curItemCount > 0 then
        if BackpackModel.curItemCount == BackpackModel.curItemID then
            Tips.show('确定删除当前穿戴物品?',function()
                BackpackView.subItem(BackpackModel.curItemCount)
                BackpackModel.curItemCount = BackpackModel.curItemCount - 1
            end,true)
        else
            BackpackView.subItem(BackpackModel.curItemCount)
            BackpackModel.curItemCount = BackpackModel.curItemCount - 1
        end
    else
        Tips.show('没有可以删除的物品')
    end
end

return BackpackController