---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/5 17:22
---

LoginController = require('Scripts.Controller.LoginController')
SignupController = require('Scripts.Controller.SignupController')