---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 11:06
---

local LoginController = {}

function LoginController.loginClick(usr, pwd, remember, autoLogin)
    local tipText = nil
    local avail = true
    if usr == "" and avail then
        tipText = "用户名为空"
        avail = false
    end

    if pwd == "" and avail then
        tipText = "密码为空"
        avail = false
    end

    if not UserDataController.getUser(usr) and avail then
        tipText = "用戶不存在"
        avail = false
    end

    if not UserDataController.checkUser(usr, pwd) and avail then
        tipText = "账号或者密码错误"
        avail = false
    end

    if avail then
        LoginController.loginSuccess(usr, pwd, remember, autoLogin)
    else
        NormalTipController.showTip(tipText)
    end
end

function LoginController.signupClick()
    LoginController.hidePanel()
    SignupController.showPanel()
end

function LoginController.showPanel()
    LoginView.show()
end

function LoginController.loginSuccess(usr, pwd, remember, autoLogin)
    UserDataController.setCurUserState(usr, pwd, remember, autoLogin)
    LoginController.hidePanel()
    SuccessController.showPanel()
end

function LoginController.hidePanel()
    LoginView.hide()
end

function LoginController.setView(usr, pwd, remember, autoLogin)
    if not remember then
        pwd = ""
    end
    LoginView.setView(usr, pwd, remember, autoLogin)
end

function LoginController.init()
    LoginController.setView(CurUser.username, CurUser.password, CurUser.remember, CurUser.autoLogin)
    if CurUser.autoLogin then
        LoginController.loginClick(CurUser.username, CurUser.password, CurUser.remember, CurUser.autoLogin)
    end
end

return LoginController