---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 14:17
---

local SuccessController = {}

function SuccessController.onQuitClick()
    DialogController.showDialog("确定退出登录？", SuccessController.quit, false)
end

function SuccessController.showPanel()
    SuccessView.show()
end

function SuccessController.quit()
    SuccessController.hidePanel()
    LoginController.setView(CurUser.username, CurUser.password, CurUser.remember, CurUser.autoLogin)
    LoginController.showPanel()
end

function SuccessController.hidePanel()
    SuccessView.hide()
end
return SuccessController