---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/24 14:59
---

local UserDataController = {}

function UserDataController.getUser(name)
    return UserDataModel.getUser(name)
end

function UserDataController.addUser(usr,pwd)
    UserDataModel.addUser(usr,pwd)
end

function UserDataController.checkUser(usr,pwd)
    return UserDataModel.checkUser(usr,pwd)
end

function UserDataController.setCurUserState(usr,pwd,remember,autoLogin)
    UserDataModel.setCurUserState(usr,pwd,remember,autoLogin)
end

function UserDataController.init()
    UserDataModel.init()
end

return UserDataController

