---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/11 11:11
---

local EventCenter = {}

EventCenter.Type = {
    SetCharacterImage = 'SetCharacterImage',
    AddBackpackItem = 'AddBackpackItem',
    SubBackpackItem = 'SubBackpackItem',
    UpdateBackpackItem = 'UpdateBackpackItem',
    RefreshBackpackItemUI = 'RefreshBackpackItemUI'
    --ShowSignupPage = 'ShowSignupPage',
    --ShowLoginPage = 'ShowLoginPage',
    --ShowHomePage = 'ShowHomePage' , 
    --ShowBackpackPage = 'ShowBackpackPage'
}

--添加事件 eventType-->事件类型  func-->方法
function EventCenter.AddListener(eventType, func)
    print('addlistener')
    if (eventType == nil or func == nil) then
        return
    end

    if (EventCenter[eventType] == nil) then
        local a = {}
        table.insert(a, func)
        EventCenter[eventType] = a
    else
        table.insert(EventCenter[eventType], func)
    end
end

--移除事件
function EventCenter.RemoveListener(eventType, func)
    if (eventType == nil or func == nil) then
        return
    end

    local a = EventCenter[eventType]
    if (a ~= nil) then
        for k, v in pairs(a) do
            if (v == func) then
                a[k] = nil
            end
        end
    end
end

--派发事件
function EventCenter.SendEvent(eventType, ...)
    if (eventType ~= nil) then
        local a = EventCenter[eventType]
        if (a ~= nil) then
            for k, v in pairs(a) do
                v(...)
            end
        end
    end
end

return EventCenter