---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 16:18
---

-- Global

function _G.Load(path, type)
    return CS.UnityEngine.Resources.Load(path, type or typeof(CS.UnityEngine.GameObject)) or nil
end

EventCenter = require('Scripts.Global.EventCenter')
Tips = require('Scripts.Global.Tips')
Users = { { username = 'admin', password = 'admin' }, { username = '1', password = '1' } }
UIDefine = require('Scripts.Global.UIDefine')
Resource = require('Scripts.Global.Resource')


-- Controllers
require('Scripts.Controller.init')

-- Models
require('Scripts.Model.init')

-- Views
require('Scripts.View.init')

UIManager = require('Scripts.Global.UIManager')


print("all variate init finish")

Resource.load('MainUI')
UIManager.showPanel('login_panel')