---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 16:18
---

-- Global
EventCenter = require('Scripts.Global.EventCenter')
Tips = require('Scripts.Global.Tips')
Users = { { username = 'admin', password = 'admin' }, { username = '1', password = '1' } }

function _G.Load(path, type)
    return CS.UnityEngine.Resources.Load(path, type) or nil
end

-- Controllers
require('Scripts.Controller.init')

-- Models
require('Scripts.Model.init')

-- Views
require('Scripts.View.init')

print("all variate init finish")

LoginController.showPanel()