---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/5 14:48
---

local Tips = {}

local btn_confirm = tips_panel.transform:Find('bg/bottomBar/btn_confirm'):GetComponent('Button')
local btn_cancel = tips_panel.transform:Find('bg/bottomBar/btn_cancel'):GetComponent('Button')
local txt_tip = tips_panel.transform:Find('bg/txt_tip'):GetComponent(typeof(CS.UnityEngine.UI.Text))

Tips.callback = nil

btn_confirm.onClick:AddListener(function()
    Tips.close()
    if Tips.callback then 
        Tips.callback()
        Tips.callback = nil
    end
end)

btn_cancel.onClick:AddListener(function()
    Tips.close()
end)

function Tips.show(content,callback,showCancelBtn)
    btn_cancel.gameObject:SetActive(showCancelBtn)
    txt_tip.text = content
    Tips.callback = callback
    tips_panel:SetActive(true)
end 

function Tips.close()
    tips_panel:SetActive(false)
    txt_tip.text = ''
end

return Tips