---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/12 14:28
---

local UIDefine = {}

LoginView = require('Scripts.View.LoginView')
SignupView = require('Scripts.View.SignupView')
HomeView = require('Scripts.View.HomeView')
CharacterView = require('Scripts.View.CharacterView')
BackpackView = require('Scripts.View.BackpackView')


UIDefine.UI = {
    MainUI = {
      path = 'Prefabs/MainUI',
      parent = nil,
      script = nil
    },
    
    login_panel = {
        path = 'Prefabs/login_panel',
        parent = 'MainUI/Login',
        script = 'Scripts.View.LoginView'
    },
    
    signup_panel = {
        path = 'Prefabs/signup_panel',
        parent = 'MainUI/Signup',
        script = 'Scripts.View.SignupView'
    },
    
    tips_panel = {
        path = 'Prefabs/tip_panel',
        parent = 'MainUI/Tip',
        script = 'Scripts.Global.Tips'
    },
    
    home_panel = {
        path = 'Prefabs/home_panel',
        parent = 'MainUI/Home',
        script = 'Scripts.View.HomeView'
    },
    
    backpack_panel = {
        path = 'Prefabs/backpack_panel',
        parent = 'MainUI/Home/home_panel',
        script = 'Scripts.View.BackpackView'
    },
    
    backpack_item = {
        path = 'Prefabs/backpack_item',
        parent = 'MainUI/Home/home_panel/backpack_panel/Viewport/Content',
        script = ''
    },
}

return UIDefine