---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/5 17:12
---

local BackpackModel = {}

BackpackModel.maxItemCount = 4 -- 背包容量
BackpackModel.curItemCount = 4 -- 当前物品数量
BackpackModel.defItemID = 3 -- 默认穿戴
BackpackModel.curItemID = 3 -- 当前穿戴

return BackpackModel