---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/5 17:12
---

local BackpackModel = {}

BackpackModel.maxItemCount = 4 -- 背包容量
BackpackModel.curItemCount = 4 -- 当前背包物品个数
BackpackModel.defItemID = 3 -- 默认穿戴
BackpackModel.curItemID = 3 -- 当前穿戴

BackpackModel.items = {
    {name = '1' ,num = 10},
    {name = '2' ,num = 20},
    {name = '3' ,num = 30},
    {name = '4' ,num = 50},
}

BackpackModel.curItems = {
    {name = '1' ,num = 10},
    {name = '2' ,num = 20},
    {name = '3' ,num = 30},
    {name = '4' ,num = 50},
}

return BackpackModel