---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dell.
--- DateTime: 2021/1/5 17:12
---

local HomeModel = {}

HomeModel.itemCount = 4
HomeModel.defItemID = 3
HomeModel.curItemID = 3

return HomeModel