---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 11:16
---

local UserDataModel = {}

function UserDataModel.addUser(mName, mPwd)
    print("adduser")
    local user = {}
    user.username = mName
    user.password = mPwd
    user.remember = false
    user.autoLogin = false
    table.insert(Users, user)
end

function UserDataModel.getUser(mName)
    print("getuser:" .. #Users)
    for key, value in pairs(Users) do   
        if value.username == mName then
            return true
        end
    end

    return false
end

function UserDataModel.checkUser(mName, mPwd)
    print("checkUser")
    for key, value in pairs(Users) do
        if value.username == mName and value.password == mPwd then
            return true
        end
    end

    return false
end

return UserDataModel